### PR TITLE
Progress with #27

### PR DESCRIPTION
**Pull request by duesee**

### CODE REVIEW

**Comment by djc** [comment]
So, I think this is an okay direction to take things in, but if you put all that in a single commit I will not be able to carefully review your changes. If you want to get this merged, it needs to be small commits that are easy to review for correctness (like, one for adding comments, one for splitting into modules, one for reformatting).

I also don't think having large swaths of commented out grammar is useful. imap-proto doesn't need to implement all of the RFC's grammar to be useful.

**Comment by sanmai-NL** [comment]
An observation. The commented out grammar does signal which part of the RFC was implemented and which wasn't yet. The general idea behind that I can understand, since I also found it somewhat challenging to map the RFC to this crate's code.

**Comment by djc** [comment]
Yes, I understood what the commented out code was trying to do. I don't agree that it is useful. Adding the RFC grammar should already help mapping the RFC to the code.

**Comment by duesee** [comment]
Yeah, not a very nice PR... I will split it :-)

The comments doesn't look very nice, yes. But they will be useful for someone implementing the remaining parsers. Especially, as the RFC is lexicographically sorted and not by relation.

There are several "clusters" of ABNF defs., which could even be used to determine what goes in which file. So maybe adding all of them is even better? This would make it very clear what (and what not) is implemented and how.

**Pull request closed without merging**
