### PR TITLE
Refactoring documentation tests

### PR DESCRIPTION
**Pull request by duesee**
Okay, I hope I've done this right. I think it is now reviewable.

### CODE REVIEW

**Comment by djc** [comment]
If you make it pass CI, I'll gladly merge it. Thanks!

**Comment by duesee** [comment]
I will remove the new unit test then. You can merge the refactorings and I will open another PR when I found how to fix the streaming issue. Nom's escaped macro worked for my test but broke others.

**Comment by duesee** [comment]
`text` is still erroneous. It should only accept 01-7f and not CR or LF.

**Comment by djc** [comment]
I squashed together your intermediate changes, left out the commented out test, fixed the compile warnings and merged the resulting commits to master:

8c0476e corrected `text` parser + `text_char` parser
11fe932 moved `text` parser to core and added ABNF
d797bd8 ABNF definitions from IMAP RFC
1f2b8e5 refactored "core" parsers

**Comment by djc** [comment]
Thanks!

**Pull request closed without merging**
