### PR TITLE
Add workaround for two consecutive spaces in response

### PR DESCRIPTION
**Pull request by vandenoever**
This is an issue with the DavMail server.

### CODE REVIEW

**Comment by djc** [comment]
The change looks good! You committed this against 0.4.1, can you rebase on top of master please?

**Comment by vandenoever** [comment]
Done

**Comment by djc** [comment]
Your test fails, I guess you're using nom 3 stuff instead of nom 4? Can you fix that up?

**Comment by vandenoever** [comment]
Right. I'll do so later today. I assumed it would stay the same.

**Comment by djc** [comment]
Here's an example fix from the nom 3 -> 4 conversion:

https://github.com/djc/tokio-imap/commit/c7ed8c8f5c905b45799768104e503fc505b83c9e#diff-c7845db764eb3d1f65eee26827f7fcc5R773

**Comment by vandenoever** [comment]
It seems to work now, locally and in the CI.

**Comment by djc** [comment]
Thanks!

**Pull request merged**
